[workspace]
members = [
    "core",
    "dh-adapted",
    "dh-eve",
    "http",
    "examples/playground",
]

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
