[workspace]
members = [
    "core",
    "data-cacher",
    "data-handler",
    "http",
    "examples/playground",
]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[profile.release-opt]
inherits = "release"
codegen-units = 1
lto = "fat"
panic = "abort"
